version: 2
jobs:
  build:
    context:
      - docker-credentials
    working_directory: /app
    docker:
      - image: docker:17.05.0-ce-git
        auth:
          username: $DOCKERHUB_USER
          password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
    environment:
      IMAGE_NAME: fomiller/megatainer
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: install docker buildx 
          command: |
            DOCKER_CLI_EXPERIENTAL=enabled
            docker buildx version
            docker context create fomiller
            docker buildx create fomille --use

      - run:
          name: Build application Docker image
          command: |
            DOCKER_BUILDKIT=1 docker buildx build --platform linux/amd64,linux/arm64 -t $IMAGE_NAME:latest -t $IMAGE_NAME:${CIRCLE_SHA1} .

      - deploy:
          name: Push application Docker image
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              docker login -u $DOCKERHUB_USER -p $DOCKERHUB_PASSWORD
              docker push $IMAGE_NAME:latest
              docker push $IMAGE_NAME:${CIRCLE_SHA1}
            fi
