version: 2

workflows:
  version: 2
  buildx-deploy:
    jobs:
      - build:
          context: docker-credentials
jobs:
  build:
    # working_directory: /app

    docker:
      - image: cimg/base:stable
        auth:
          username: $DOCKERHUB_USER
          password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference

    environment:
      IMAGE_NAME: fomiller/megatainer
      BUILDX_PLATFORMS: linux/amd64,linux/arm64
        
    steps:
      - checkout

      - setup_remote_docker:
          version: 20.10.11

      - run: 
          name: Docker login 
          command: |
            docker login -u $DOCKERHUB_USER -p $DOCKERHUB_PASSWORD

      - run:
          name: Build and push Docker image
          command: |
            docker context create buildx-builder
            docker buildx create --use buildx-builder
            docker buildx build --push \
              --platform $BUILDX_PLATFORMS \
              -t $IMAGE_NAME:latest \
              -t $IMAGE_NAME:${CIRCLE_SHA1} \
              -t $IMAGE_NAME:${CIRCLE_BRANCH} .
