version: 2
jobs:
  build:
    context:
      - docker-credentials
    working_directory: /app
    docker:
      - image: docker:stable
        auth:
          username: $DOCKERHUB_USER
          password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
    environment:
      IMAGE_NAME: fomiller/megatainer
    steps:
      - checkout
      - setup_remote_docker:
          version: 18.09.3
      - run:
          name: install docker buildx 
          command: |
            apk add curl
            mkdir -vp ~/.docker/cli-plugins/
            curl --silent -L --output ~/.docker/cli-plugins/docker-buildx https://github.com/docker/buildx/releases/download/v0.3.1/buildx-v0.3.1.linux-amd64
            chmod a+x ~/.docker/cli-plugins/docker-buildx
            docker buildx version

      - run:
          name: Build application Docker image
          command: |
            docker build \
              --platform linux/arm64 \
              --tag $IMAGE_NAME:latest -t $IMAGE_NAME:${CIRCLE_SHA1} .

      - deploy:
          name: Push application Docker image
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              docker login -u $DOCKERHUB_USER -p $DOCKERHUB_PASSWORD
              docker push $IMAGE_NAME:latest
              docker push $IMAGE_NAME:${CIRCLE_SHA1}
            fi
